/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "fifo.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_read(void);
extern void test_write(void);
extern void test_readEmptyBuffer(void);
extern void test_writeMoreThanSizeOfBuffer(void);
extern void test_writeWrapAround(void);
extern void test_peekAndPopWrapAround(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("fast_fifo_test.c");
  run_test(test_read, "test_read", 57);
  run_test(test_write, "test_write", 81);
  run_test(test_readEmptyBuffer, "test_readEmptyBuffer", 109);
  run_test(test_writeMoreThanSizeOfBuffer, "test_writeMoreThanSizeOfBuffer", 122);
  run_test(test_writeWrapAround, "test_writeWrapAround", 143);
  run_test(test_peekAndPopWrapAround, "test_peekAndPopWrapAround", 193);

  return UnityEnd();
}
