# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sign_buddy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10sign_buddy.proto\"=\n\x0eSBPGestureData\x12\x0e\n\x06letter\x18\x01 \x02(\t\x12\x1b\n\x07samples\x18\x02 \x03(\x0b\x32\n.SBPSample\"_\n\nSBPMessage\x12\n\n\x02id\x18\x01 \x02(\r\x12\x1c\n\x06sample\x18\x02 \x01(\x0b\x32\n.SBPSampleH\x00\x12\x1c\n\x06status\x18\x03 \x01(\x0b\x32\n.SBPStatusH\x00\x42\t\n\x07payload\"\xd5\x04\n\tSBPSample\x12\x11\n\tsample_id\x18\x01 \x02(\r\x12$\n\x08imu_data\x18\x02 \x02(\x0b\x32\x12.SBPSample.IMUData\x12&\n\tflex_data\x18\x03 \x02(\x0b\x32\x13.SBPSample.FlexData\x12(\n\ntouch_data\x18\x04 \x02(\x0b\x32\x14.SBPSample.TouchData\x1ao\n\x07IMUData\x12\r\n\x05\x65ul_h\x18\x01 \x02(\x11\x12\r\n\x05\x65ul_r\x18\x02 \x02(\x11\x12\r\n\x05\x65ul_p\x18\x03 \x02(\x11\x12\x11\n\tlin_acc_x\x18\x04 \x02(\x11\x12\x11\n\tlin_acc_y\x18\x05 \x02(\x11\x12\x11\n\tlin_acc_z\x18\x06 \x02(\x11\x1ao\n\x08\x46lexData\x12\x12\n\nflex_thumb\x18\x01 \x02(\r\x12\x12\n\nflex_index\x18\x02 \x02(\r\x12\x13\n\x0b\x66lex_middle\x18\x03 \x02(\r\x12\x11\n\tflex_ring\x18\x04 \x02(\r\x12\x13\n\x0b\x66lex_little\x18\x05 \x02(\r\x1a\xda\x01\n\tTouchData\x12\x0f\n\x07touch_1\x18\x01 \x02(\x08\x12\x0f\n\x07touch_2\x18\x02 \x02(\x08\x12\x0f\n\x07touch_3\x18\x03 \x02(\x08\x12\x0f\n\x07touch_4\x18\x04 \x02(\x08\x12\x0f\n\x07touch_5\x18\x05 \x02(\x08\x12\x0f\n\x07touch_6\x18\x06 \x02(\x08\x12\x0f\n\x07touch_7\x18\x07 \x02(\x08\x12\x0f\n\x07touch_8\x18\x08 \x02(\x08\x12\x0f\n\x07touch_9\x18\t \x02(\x08\x12\x10\n\x08touch_10\x18\n \x02(\x08\x12\x10\n\x08touch_11\x18\x0b \x02(\x08\x12\x10\n\x08touch_12\x18\x0c \x02(\x08\"\x9d\x01\n\tSBPStatus\x12\x17\n\x0f\x62\x61ttery_voltage\x18\x01 \x02(\r\x12\x1c\n\x14imu_sys_calib_status\x18\x02 \x02(\r\x12\x1c\n\x14imu_mag_calib_status\x18\x03 \x02(\r\x12\x1c\n\x14imu_acc_calib_status\x18\x04 \x02(\r\x12\x1d\n\x15imu_gyro_calib_status\x18\x05 \x02(\r')



_SBPGESTUREDATA = DESCRIPTOR.message_types_by_name['SBPGestureData']
_SBPMESSAGE = DESCRIPTOR.message_types_by_name['SBPMessage']
_SBPSAMPLE = DESCRIPTOR.message_types_by_name['SBPSample']
_SBPSAMPLE_IMUDATA = _SBPSAMPLE.nested_types_by_name['IMUData']
_SBPSAMPLE_FLEXDATA = _SBPSAMPLE.nested_types_by_name['FlexData']
_SBPSAMPLE_TOUCHDATA = _SBPSAMPLE.nested_types_by_name['TouchData']
_SBPSTATUS = DESCRIPTOR.message_types_by_name['SBPStatus']
SBPGestureData = _reflection.GeneratedProtocolMessageType('SBPGestureData', (_message.Message,), {
  'DESCRIPTOR' : _SBPGESTUREDATA,
  '__module__' : 'sign_buddy_pb2'
  # @@protoc_insertion_point(class_scope:SBPGestureData)
  })
_sym_db.RegisterMessage(SBPGestureData)

SBPMessage = _reflection.GeneratedProtocolMessageType('SBPMessage', (_message.Message,), {
  'DESCRIPTOR' : _SBPMESSAGE,
  '__module__' : 'sign_buddy_pb2'
  # @@protoc_insertion_point(class_scope:SBPMessage)
  })
_sym_db.RegisterMessage(SBPMessage)

SBPSample = _reflection.GeneratedProtocolMessageType('SBPSample', (_message.Message,), {

  'IMUData' : _reflection.GeneratedProtocolMessageType('IMUData', (_message.Message,), {
    'DESCRIPTOR' : _SBPSAMPLE_IMUDATA,
    '__module__' : 'sign_buddy_pb2'
    # @@protoc_insertion_point(class_scope:SBPSample.IMUData)
    })
  ,

  'FlexData' : _reflection.GeneratedProtocolMessageType('FlexData', (_message.Message,), {
    'DESCRIPTOR' : _SBPSAMPLE_FLEXDATA,
    '__module__' : 'sign_buddy_pb2'
    # @@protoc_insertion_point(class_scope:SBPSample.FlexData)
    })
  ,

  'TouchData' : _reflection.GeneratedProtocolMessageType('TouchData', (_message.Message,), {
    'DESCRIPTOR' : _SBPSAMPLE_TOUCHDATA,
    '__module__' : 'sign_buddy_pb2'
    # @@protoc_insertion_point(class_scope:SBPSample.TouchData)
    })
  ,
  'DESCRIPTOR' : _SBPSAMPLE,
  '__module__' : 'sign_buddy_pb2'
  # @@protoc_insertion_point(class_scope:SBPSample)
  })
_sym_db.RegisterMessage(SBPSample)
_sym_db.RegisterMessage(SBPSample.IMUData)
_sym_db.RegisterMessage(SBPSample.FlexData)
_sym_db.RegisterMessage(SBPSample.TouchData)

SBPStatus = _reflection.GeneratedProtocolMessageType('SBPStatus', (_message.Message,), {
  'DESCRIPTOR' : _SBPSTATUS,
  '__module__' : 'sign_buddy_pb2'
  # @@protoc_insertion_point(class_scope:SBPStatus)
  })
_sym_db.RegisterMessage(SBPStatus)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SBPGESTUREDATA._serialized_start=20
  _SBPGESTUREDATA._serialized_end=81
  _SBPMESSAGE._serialized_start=83
  _SBPMESSAGE._serialized_end=178
  _SBPSAMPLE._serialized_start=181
  _SBPSAMPLE._serialized_end=778
  _SBPSAMPLE_IMUDATA._serialized_start=333
  _SBPSAMPLE_IMUDATA._serialized_end=444
  _SBPSAMPLE_FLEXDATA._serialized_start=446
  _SBPSAMPLE_FLEXDATA._serialized_end=557
  _SBPSAMPLE_TOUCHDATA._serialized_start=560
  _SBPSAMPLE_TOUCHDATA._serialized_end=778
  _SBPSTATUS._serialized_start=781
  _SBPSTATUS._serialized_end=938
# @@protoc_insertion_point(module_scope)
