/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "SignBuddy.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GestureData, GestureData, AUTO)


PB_BIND(Message, Message, AUTO)


PB_BIND(Sample, Sample, AUTO)


PB_BIND(Sample_IMUData, Sample_IMUData, AUTO)


PB_BIND(Sample_FlexData, Sample_FlexData, AUTO)


PB_BIND(Sample_TouchData, Sample_TouchData, AUTO)


PB_BIND(Status, Status, AUTO)
