/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "sign_buddy.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SBPGestureData, SBPGestureData, AUTO)


PB_BIND(SBPMessage, SBPMessage, AUTO)


PB_BIND(SBPSample, SBPSample, AUTO)


PB_BIND(SBPSample_IMUData, SBPSample_IMUData, AUTO)


PB_BIND(SBPSample_FlexData, SBPSample_FlexData, AUTO)


PB_BIND(SBPSample_TouchData, SBPSample_TouchData, AUTO)


PB_BIND(SBPStatus, SBPStatus, AUTO)



