name: Run Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Cache Docker
      id: cache-docker
      uses: actions/cache@v2
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-docker

    - name: Build docker image
      if: steps.cache-docker.outputs.cache-hit != 'true'
      run: |
        bash firmware/tools/build_docker_image.sh
        echo "Exited with '$?'"

    - name: Build the nucleo firmware
      run: |
        bash firmware/tools/compile.sh NUCLEO
        echo "Exited with '$?'"

    - name: Clean the firmware
      run: |
        sudo make clean -C firmware
        echo "Exited with '$?'"

